from pathlib import Path
import numpy as np


def _quaternion_to_rotation_matrix(qx: float, qy: float, qz: float, qw: float) -> np.ndarray:
    """
    Convert a quaternion in x, y, z, w order to a 3x3 rotation matrix.
    """
    q = np.array([qx, qy, qz, qw], dtype=np.float64)
    norm = np.linalg.norm(q)

    if norm < 1e-12:
        raise ValueError("Invalid calibration quaternion: norm is zero")

    qx, qy, qz, qw = q / norm

    return np.array([
        [1.0 - 2.0 * (qy * qy + qz * qz), 2.0 * (qx * qy - qz * qw), 2.0 * (qx * qz + qy * qw)],
        [2.0 * (qx * qy + qz * qw), 1.0 - 2.0 * (qx * qx + qz * qz), 2.0 * (qy * qz - qx * qw)],
        [2.0 * (qx * qz - qy * qw), 2.0 * (qy * qz + qx * qw), 1.0 - 2.0 * (qx * qx + qy * qy)],
    ], dtype=np.float64)


def _load_yaml(path: Path) -> dict:
    try:
        import yaml
    except ImportError as exc:
        return _load_simple_ros_tf_yaml(path)

    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if not isinstance(data, dict):
        raise ValueError(f"Invalid YAML calibration file: {path}")

    return data


def _load_simple_ros_tf_yaml(path: Path) -> dict:
    """
    Minimal fallback parser for the generated ROS 2 static transform YAML.

    This keeps inference free of a PyYAML dependency for the small, fixed
    calibration file generated by tf2 tooling.
    """
    params = {}
    section = None

    with open(path, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.split("#", 1)[0].strip()

            if not line:
                continue

            if line.endswith(":"):
                key = line[:-1].strip().strip("\"'")

                if key in {"translation", "rotation"}:
                    section = key
                    params[section] = {}
                else:
                    section = None

                continue

            if ":" not in line:
                continue

            key, value = line.split(":", 1)
            key = key.strip().strip("\"'")
            value = value.strip().strip("\"'")

            if section in {"translation", "rotation"}:
                params[section][key] = float(value)
            elif value:
                params[key] = value

    if "translation" not in params or "rotation" not in params:
        raise ValueError(f"Invalid ROS transform YAML calibration file: {path}")

    return {"ros__parameters": params}


def _load_T_base_cam_from_ros_yaml(path: Path) -> np.ndarray:
    """
    Load a ROS 2 static transform YAML.

    Expected format:
        /**:
          ros__parameters:
            frame_id: base frame
            child_frame_id: camera frame
            translation: {x, y, z}
            rotation: {x, y, z, w}
    """
    data = _load_yaml(path)

    if "/**" in data:
        data = data["/**"]

    params = data.get("ros__parameters", data)
    translation = params.get("translation")
    rotation = params.get("rotation")

    if not isinstance(translation, dict) or not isinstance(rotation, dict):
        raise ValueError(
            "Expected ROS YAML calibration with translation {x,y,z} "
            "and rotation quaternion {x,y,z,w}"
        )

    t = np.array([
        float(translation["x"]),
        float(translation["y"]),
        float(translation["z"]),
    ], dtype=np.float64)

    R = _quaternion_to_rotation_matrix(
        qx=float(rotation["x"]),
        qy=float(rotation["y"]),
        qz=float(rotation["z"]),
        qw=float(rotation["w"]),
    )

    T = np.eye(4, dtype=np.float64)
    T[:3, :3] = R
    T[:3, 3] = t

    return T


def load_T_base_cam(path: str | Path) -> np.ndarray:
    """
    Load camera-to-robot calibration.

    Supported:
        .npy:
            4x4 homogeneous matrix.

        .yaml / .yml:
            ROS 2 static transform with translation and quaternion rotation.

    Units must match the Zivid point cloud, normally mm.
    """
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(f"Calibration matrix not found: {path}")

    if path.suffix.lower() == ".npy":
        T = np.load(path)
    elif path.suffix.lower() in {".yaml", ".yml"}:
        T = _load_T_base_cam_from_ros_yaml(path)
    else:
        raise ValueError(f"Unsupported calibration format: {path.suffix}")

    if T.shape != (4, 4):
        raise ValueError(f"Expected 4x4 matrix, got {T.shape}")

    return T.astype(np.float64)


def make_T_cam_approach(pose_result: dict, clearance_mm: float = 20.0) -> np.ndarray:
    """
    Create a safe approach pose in camera frame.

    The approach point is placed outside the eye along the trocar axis:
        p_approach = p_entry - clearance_mm * v_trocar
    """
    T_cam_trocar = np.asarray(pose_result["T_cam_trocar"], dtype=np.float64).copy()

    p_entry = np.asarray(pose_result["p_entry_mm"], dtype=np.float64)
    v = np.asarray(pose_result["v_trocar"], dtype=np.float64)

    v_norm = np.linalg.norm(v)

    if v_norm < 1e-9:
        raise ValueError("Invalid trocar axis: norm is zero")

    v = v / v_norm

    p_approach = p_entry - clearance_mm * v

    T_cam_approach = T_cam_trocar.copy()
    T_cam_approach[:3, 3] = p_approach

    return T_cam_approach


def transform_pose(T_base_cam: np.ndarray, T_cam_target: np.ndarray) -> np.ndarray:
    """
    Transform a pose from camera frame to robot base frame.
    """
    return T_base_cam @ T_cam_target


def transform_point(T_base_cam: np.ndarray, p_cam_mm: np.ndarray) -> np.ndarray:
    """
    Transform a 3D point from camera frame to robot base frame. For debugging: to obtain
    eye_center_mm, eye_radius_mm, p_entry_mm, v_trocar in the robot frame.
    """
    p_h = np.array([p_cam_mm[0], p_cam_mm[1], p_cam_mm[2], 1.0])
    return (T_base_cam @ p_h)[:3]
